// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Data.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "German physicist and mathematician who developed the theory of relativity",
                            Name = "Albert Einstein"
                        },
                        new
                        {
                            Id = 2,
                            Description = "English novelist known for her works of romantic fiction",
                            Name = "Jane Austen"
                        },
                        new
                        {
                            Id = 3,
                            Description = "English theoretical physicist and cosmologist",
                            Name = "Stephen Hawking"
                        },
                        new
                        {
                            Id = 4,
                            Description = "British author, philanthropist, film producer, television producer and screenwriter",
                            Name = "J.K. Rowling"
                        },
                        new
                        {
                            Id = 5,
                            Description = "English writer known for her detective novels",
                            Name = "Agatha Christie"
                        },
                        new
                        {
                            Id = 6,
                            Description = "American astrophysicist, planetary scientist, author, and science communicator",
                            Name = "Neil deGrasse Tyson"
                        },
                        new
                        {
                            Id = 7,
                            Description = "American writer and professor of biochemistry",
                            Name = "Isaac Asimov"
                        },
                        new
                        {
                            Id = 8,
                            Description = "American author known for his thriller novels",
                            Name = "Dan Brown"
                        },
                        new
                        {
                            Id = 9,
                            Description = "American lawyer and author who served as the First Lady of the United States from 2009 to 2017",
                            Name = "Michelle Obama"
                        },
                        new
                        {
                            Id = 10,
                            Description = "English novelist, essayist, journalist and critic, best known for his dystopian novel 1984 and the allegorical novella Animal Farm",
                            Name = "George Orwell"
                        });
                });

            modelBuilder.Entity("API.Data.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Edition")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("PublishYear")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 3,
                            CoverImagePath = "~/1.jpg",
                            Description = "A theoretical physicist's introduction to the theory of relativity",
                            Edition = "1st edition",
                            ISBN = "812147409117",
                            Language = "English",
                            PageCount = 160,
                            Price = 150000,
                            PublishYear = "1916",
                            PublisherId = 1,
                            Quantity = 5,
                            Title = "Relativity: The Special and General Theory"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CategoryId = 4,
                            CoverImagePath = "~/1.jpg",
                            Description = "A romantic novel about the pride and prejudices of the British upper class in the early 19th century",
                            Edition = "2nd edition",
                            ISBN = "031578731037",
                            Language = "English",
                            PageCount = 279,
                            Price = 100000,
                            PublishYear = "1813",
                            PublisherId = 2,
                            Quantity = 3,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            CategoryId = 3,
                            CoverImagePath = "~/1.jpg",
                            Description = "A popular science book about cosmology and the universe",
                            Edition = "10th anniversary edition",
                            ISBN = "651061038029",
                            Language = "English",
                            PageCount = 212,
                            Price = 120000,
                            PublishYear = "1988",
                            PublisherId = 3,
                            Quantity = 7,
                            Title = "A Brief History of Time"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            CategoryId = 4,
                            CoverImagePath = "~/1.jpg",
                            Description = "The first book in the Harry Potter series, a fantasy novel about a young wizard and his friends at Hogwarts School of Witchcraft and Wizardry",
                            Edition = "1st edition",
                            ISBN = "331976562909",
                            Language = "English",
                            PageCount = 223,
                            Price = 130000,
                            PublishYear = "1997",
                            PublisherId = 4,
                            Quantity = 2,
                            Title = "Harry Potter and the Philosopher's Stone"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            CategoryId = 1,
                            CoverImagePath = "~/1.jpg",
                            Description = "A detective novel about a murder on a train, featuring famous detective Hercule Poirot",
                            Edition = "2nd edition",
                            ISBN = "151983459085",
                            Language = "English",
                            PageCount = 256,
                            Price = 110000,
                            PublishYear = "1934",
                            PublisherId = 1,
                            Quantity = 4,
                            Title = "Murder on the Orient Express"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 6,
                            CategoryId = 3,
                            CoverImagePath = "~/1.jpg",
                            Description = "An introduction to astrophysics for laypeople",
                            Edition = "1st edition",
                            ISBN = "879969938708",
                            Language = "English",
                            PageCount = 224,
                            Price = 140000,
                            PublishYear = "2017",
                            PublisherId = 5,
                            Quantity = 6,
                            Title = "Astrophysics for People in a Hurry"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 7,
                            CategoryId = 2,
                            CoverImagePath = "~/1.jpg",
                            Description = "An annotated edition of the classic satire by Jonathan Swift",
                            Edition = "3rd edition",
                            ISBN = "719751729826",
                            Language = "English",
                            PageCount = 522,
                            Price = 105000,
                            PublishYear = "1960",
                            PublisherId = 2,
                            Quantity = 1,
                            Title = "The Annotated Gulliver's Travels"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 8,
                            CategoryId = 1,
                            CoverImagePath = "~/1.jpg",
                            Description = "A thriller novel by American author Dan Brown",
                            Edition = "First edition",
                            ISBN = "915817301724",
                            Language = "English",
                            PageCount = 481,
                            Price = 150000,
                            PublishYear = "2003",
                            PublisherId = 4,
                            Quantity = 10,
                            Title = "The Da Vinci Code"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 9,
                            CategoryId = 5,
                            CoverImagePath = "~/1.jpg",
                            Description = "An autobiography by Michelle Obama",
                            Edition = "First edition",
                            ISBN = "814172283437",
                            Language = "English",
                            PageCount = 426,
                            Price = 250000,
                            PublishYear = "2018",
                            PublisherId = 3,
                            Quantity = 8,
                            Title = "Becoming"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 9,
                            CategoryId = 4,
                            CoverImagePath = "~/1.jpg",
                            Description = "A children's fantasy novel by J.R.R. Tolkien",
                            Edition = "Revised edition",
                            ISBN = "221239864699",
                            Language = "English",
                            PageCount = 310,
                            Price = 120000,
                            PublishYear = "1937",
                            PublisherId = 1,
                            Quantity = 12,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 3,
                            CategoryId = 3,
                            CoverImagePath = "~/1.jpg",
                            Description = "A popular science book by British physicist Stephen Hawking",
                            Edition = "First edition",
                            ISBN = "314467000238",
                            Language = "English",
                            PageCount = 212,
                            Price = 180000,
                            PublishYear = "1988",
                            PublisherId = 2,
                            Quantity = 5,
                            Title = "A Brief History of Time"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 2,
                            CategoryId = 4,
                            CoverImagePath = "~/1.jpg",
                            Description = "A romantic novel by English author Jane Austen",
                            Edition = "First edition",
                            ISBN = "299561579059",
                            Language = "English",
                            PageCount = 279,
                            Price = 90000,
                            PublishYear = "1813",
                            PublisherId = 5,
                            Quantity = 15,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 3,
                            CategoryId = 3,
                            CoverImagePath = "~/1.jpg",
                            Description = "A popular-science book by British physicists Stephen Hawking and Leonard Mlodinow",
                            Edition = "First edition",
                            ISBN = "608194139567",
                            Language = "English",
                            PageCount = 198,
                            Price = 200000,
                            PublishYear = "2010",
                            PublisherId = 4,
                            Quantity = 3,
                            Title = "The Grand Design"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 5,
                            CategoryId = 1,
                            CoverImagePath = "~/1.jpg",
                            Description = "A detective novel by Agatha Christie",
                            Edition = "First edition",
                            ISBN = "899539460748",
                            Language = "English",
                            PageCount = 288,
                            Price = 85000,
                            PublishYear = "1926",
                            PublisherId = 1,
                            Quantity = 6,
                            Title = "The Murder of Roger Ackroyd"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 8,
                            CategoryId = 4,
                            CoverImagePath = "~/1.jpg",
                            Description = "A novel by John Green",
                            Edition = "First edition",
                            ISBN = "297136524734",
                            Language = "English",
                            PageCount = 313,
                            Price = 170000,
                            PublishYear = "2012",
                            PublisherId = 2,
                            Quantity = 9,
                            Title = "The Fault in Our Stars"
                        });
                });

            modelBuilder.Entity("API.Data.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Mystery and crime novels",
                            Name = "Detective"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Books about art, artists and art history",
                            Name = "Art"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Books about natural science, mathematics, and technology",
                            Name = "Science"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Books about imaginary people and events",
                            Name = "Fiction"
                        },
                        new
                        {
                            CategoryId = 5,
                            Description = "Books about historical events and figures",
                            Name = "History"
                        },
                        new
                        {
                            CategoryId = 6,
                            Description = "Books about people's lives and experiences",
                            Name = "Biography"
                        },
                        new
                        {
                            CategoryId = 7,
                            Description = "Books about travel destinations and experiences",
                            Name = "Travel"
                        },
                        new
                        {
                            CategoryId = 8,
                            Description = "Books about business management, entrepreneurship, and finance",
                            Name = "Business"
                        },
                        new
                        {
                            CategoryId = 9,
                            Description = "Books about cooking techniques, recipes, and ingredients",
                            Name = "Cooking"
                        },
                        new
                        {
                            CategoryId = 10,
                            Description = "Books about personal development, motivation, and success",
                            Name = "Self-help"
                        });
                });

            modelBuilder.Entity("API.Data.Instance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("StatusId");

                    b.ToTable("Instances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 3,
                            BookId = 3,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 4,
                            BookId = 4,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 5,
                            BookId = 5,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 6,
                            BookId = 6,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 7,
                            BookId = 7,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 8,
                            BookId = 8,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 9,
                            BookId = 9,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 10,
                            BookId = 10,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 11,
                            BookId = 11,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 12,
                            BookId = 12,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 13,
                            BookId = 13,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 14,
                            BookId = 14,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 15,
                            BookId = 15,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 16,
                            BookId = 1,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 17,
                            BookId = 2,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 18,
                            BookId = 3,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 19,
                            BookId = 4,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 20,
                            BookId = 5,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 21,
                            BookId = 6,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 22,
                            BookId = 7,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 23,
                            BookId = 8,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 24,
                            BookId = 9,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 25,
                            BookId = 10,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 26,
                            BookId = 11,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 27,
                            BookId = 12,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 28,
                            BookId = 13,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 29,
                            BookId = 14,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 30,
                            BookId = 15,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 31,
                            BookId = 1,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 32,
                            BookId = 2,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 33,
                            BookId = 3,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 34,
                            BookId = 4,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 35,
                            BookId = 5,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 36,
                            BookId = 6,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 37,
                            BookId = 7,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 38,
                            BookId = 8,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 39,
                            BookId = 9,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 40,
                            BookId = 10,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 41,
                            BookId = 11,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 42,
                            BookId = 12,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 43,
                            BookId = 13,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 44,
                            BookId = 14,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 45,
                            BookId = 15,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 46,
                            BookId = 1,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 47,
                            BookId = 2,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 48,
                            BookId = 3,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 49,
                            BookId = 4,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 50,
                            BookId = 5,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 51,
                            BookId = 6,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 52,
                            BookId = 7,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 53,
                            BookId = 8,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 54,
                            BookId = 9,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 55,
                            BookId = 10,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 56,
                            BookId = 11,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 57,
                            BookId = 12,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 58,
                            BookId = 13,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 59,
                            BookId = 14,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 60,
                            BookId = 15,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 61,
                            BookId = 1,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 62,
                            BookId = 2,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 63,
                            BookId = 3,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 64,
                            BookId = 4,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 65,
                            BookId = 5,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 66,
                            BookId = 6,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 67,
                            BookId = 7,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 68,
                            BookId = 8,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 69,
                            BookId = 9,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 70,
                            BookId = 10,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 71,
                            BookId = 11,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 72,
                            BookId = 12,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 73,
                            BookId = 13,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 74,
                            BookId = 14,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 75,
                            BookId = 15,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 76,
                            BookId = 1,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 77,
                            BookId = 2,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 78,
                            BookId = 3,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 79,
                            BookId = 4,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 80,
                            BookId = 5,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 81,
                            BookId = 6,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 82,
                            BookId = 7,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 83,
                            BookId = 8,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 84,
                            BookId = 9,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 85,
                            BookId = 10,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 86,
                            BookId = 11,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 87,
                            BookId = 12,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 88,
                            BookId = 13,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 89,
                            BookId = 14,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 90,
                            BookId = 15,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 91,
                            BookId = 1,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 92,
                            BookId = 2,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 93,
                            BookId = 3,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 94,
                            BookId = 4,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 95,
                            BookId = 5,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 96,
                            BookId = 6,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 97,
                            BookId = 7,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 98,
                            BookId = 8,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 99,
                            BookId = 9,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 100,
                            BookId = 10,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 101,
                            BookId = 11,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 102,
                            BookId = 12,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 103,
                            BookId = 13,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 104,
                            BookId = 14,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 105,
                            BookId = 15,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 106,
                            BookId = 1,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 107,
                            BookId = 2,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 108,
                            BookId = 3,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 109,
                            BookId = 4,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 110,
                            BookId = 5,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 111,
                            BookId = 6,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 112,
                            BookId = 7,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 113,
                            BookId = 8,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 114,
                            BookId = 9,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 115,
                            BookId = 10,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 116,
                            BookId = 11,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 117,
                            BookId = 12,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 118,
                            BookId = 13,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 119,
                            BookId = 14,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 120,
                            BookId = 15,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 121,
                            BookId = 1,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 122,
                            BookId = 2,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 123,
                            BookId = 3,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 124,
                            BookId = 4,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 125,
                            BookId = 5,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 126,
                            BookId = 6,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 127,
                            BookId = 7,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 128,
                            BookId = 8,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 129,
                            BookId = 9,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 130,
                            BookId = 10,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 131,
                            BookId = 11,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 132,
                            BookId = 12,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 133,
                            BookId = 13,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 134,
                            BookId = 14,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 135,
                            BookId = 15,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 136,
                            BookId = 1,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 137,
                            BookId = 2,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 138,
                            BookId = 3,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 139,
                            BookId = 4,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 140,
                            BookId = 5,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 141,
                            BookId = 6,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 142,
                            BookId = 7,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 143,
                            BookId = 8,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 144,
                            BookId = 9,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 145,
                            BookId = 10,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 146,
                            BookId = 11,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 147,
                            BookId = 12,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 148,
                            BookId = 13,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 149,
                            BookId = 14,
                            StatusId = 1
                        },
                        new
                        {
                            Id = 150,
                            BookId = 15,
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("API.Data.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BorrowedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstanceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReturnedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId");

                    b.HasIndex("UserId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("API.Data.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "One of the largest and most prestigious English-language publishers.",
                            Name = "Penguin Books"
                        },
                        new
                        {
                            Id = 2,
                            Description = "An American publishing company, one of the world's largest.",
                            Name = "HarperCollins"
                        },
                        new
                        {
                            Id = 3,
                            Description = "An American book publisher and the largest general-interest paperback publisher in the world.",
                            Name = "Random House"
                        },
                        new
                        {
                            Id = 4,
                            Description = "An American publishing company and a division of ViacomCBS.",
                            Name = "Simon & Schuster"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A global trade publishing company, owned by Holtzbrinck Publishing Group.",
                            Name = "Macmillan Publishers"
                        },
                        new
                        {
                            Id = 6,
                            Description = "The largest university press in the world, publishing in 70 languages and 190 countries.",
                            Name = "Oxford University Press"
                        },
                        new
                        {
                            Id = 7,
                            Description = "The publishing business of the University of Cambridge, one of the world's oldest universities.",
                            Name = "Cambridge University Press"
                        },
                        new
                        {
                            Id = 8,
                            Description = "A global academic publishing company, the product of a merger between Springer Science+Business Media and Nature Publishing Group.",
                            Name = "Springer Nature"
                        },
                        new
                        {
                            Id = 9,
                            Description = "The world's third-largest trade book publisher, headquartered in France.",
                            Name = "Hachette Livre"
                        },
                        new
                        {
                            Id = 10,
                            Description = "A British independent publishing house, best known for publishing the Harry Potter series.",
                            Name = "Bloomsbury Publishing"
                        });
                });

            modelBuilder.Entity("API.Data.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Reader"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Librarian"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("API.Data.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Available"
                        },
                        new
                        {
                            Id = 2,
                            Name = "On Loan"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Broken"
                        });
                });

            modelBuilder.Entity("API.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ice@gmail.com",
                            IsActived = true,
                            IsOnline = false,
                            Name = "Ice",
                            Password = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            RoleId = 3,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ceri@gmail.com",
                            IsActived = true,
                            IsOnline = false,
                            Name = "Ceri",
                            Password = "LEReHATfTiR8IIkkW2j8gR9yj30w/xSm1kpPqsWOYnA=",
                            RoleId = 2,
                            Username = "librarian"
                        },
                        new
                        {
                            Id = 3,
                            Email = "user1@gmail.com",
                            IsActived = true,
                            IsOnline = false,
                            Name = "User1",
                            Password = "CgQblGLKpKMbrDVn4Lbm/ZEAeH2yq0M9lvbReMq/zpA=",
                            RoleId = 1,
                            Username = "user1"
                        },
                        new
                        {
                            Id = 4,
                            Email = "user2@gmail.com",
                            IsActived = true,
                            IsOnline = false,
                            Name = "User2",
                            Password = "YCXRj+SKvUUWhSjxioLiZd2Y1CGnCEqgn2GzQXA5AaM=",
                            RoleId = 1,
                            Username = "user2"
                        },
                        new
                        {
                            Id = 5,
                            Email = "user3@gmail.com",
                            IsActived = true,
                            IsOnline = false,
                            Name = "User3",
                            Password = "WGD68CtrxiIrpaylI1YPDjZMzYtnvuSG/ov3wB1JLMs=",
                            RoleId = 1,
                            Username = "user3"
                        });
                });

            modelBuilder.Entity("API.Data.Book", b =>
                {
                    b.HasOne("API.Data.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Data.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Data.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("API.Data.Instance", b =>
                {
                    b.HasOne("API.Data.Book", "Book")
                        .WithMany("Instance")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Data.Status", "Status")
                        .WithMany("Instances")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("API.Data.Loan", b =>
                {
                    b.HasOne("API.Data.Instance", "Instance")
                        .WithMany("Loans")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Data.User", "User")
                        .WithMany("Loans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Data.User", b =>
                {
                    b.HasOne("API.Data.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("API.Data.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("API.Data.Book", b =>
                {
                    b.Navigation("Instance");
                });

            modelBuilder.Entity("API.Data.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("API.Data.Instance", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("API.Data.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("API.Data.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("API.Data.Status", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("API.Data.User", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
